export const ADD_MESSAGE = 'ADD_MESSAGE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const ADD_FILE_PREVIEW = 'ADD_FILE_PREVIEW';
export const CHANGE_FILE_PREVIEW = 'CHANGE_FILE_PREVIEW';
export const DELETE_FILE_PREVIEW = 'DELETE_FILE_PREVIEW';
export const CLEAR_FILES_PREVIEW = 'CLEAR_FILES_PREVIEW';