export const ADD_MESSAGE = 'ADD_MESSAGE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const ADD_ATTACHED_FILE = 'ADD_ATTACHED_FILE';
export const CHANGE_ATTACHED_FILE = 'CHANGE_ATTACHED_FILE';
export const DELETE_ATTACHED_FILE = 'DELETE_ATTACHED_FILE';
export const CLEAR_ATTACHED_FILES= 'CLEAR_ATTACHED_FILES';